version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
